### ISSUE TITLE
Document the whole Airtable schema thing

### ISSUE THREAD

**Issue by cubeghost** [bedstuystrong/firebase-functions#26]

**Comment by maybejustmaybe** [comment]
We have this! 

https://airtable.com/invite/l?inviteId=invnQ1KEABfRaWZP9&inviteToken=6e56d7641df7833e6ef84b4b97412ace002d775c08ad768b3b941d126e71c706

**Comment by maybejustmaybe** [comment]
NOTE that I pulled the above link from our BSS Systems doc: bedstuystrong.com/systems
