### ISSUE TITLE
Poll the volunteers from table and populate slack user info

### ISSUE THREAD

**Issue by maybejustmaybe** [bedstuystrong/firebase-functions#28]
We are currently doing this via a zapier integration. We should use our firebase infrastructure to do this now. 

Tasks:
- [ ] Add a `Status` column to our `Volunteers` table in airtable
- [ ] Add a `Status` entry to the `Volunteers` schema
- [ ] Add a scheduled function in `poll.js` that uses `pollTable` (refer to `reimbursements` as an example)
- [ ] Populate the Slack ID and Slack handle in the airtable record (refer to the `Volunteers: Populate Slack Info` script for reference)

Bonus: #23

**Comment by kreig303** [comment]
@maybejustmaybe 

-[ ] airtable access
-[ ] slack workspace admin access

**Comment by kreig303** [comment]
also one of the vols offered to do PMy stuff... might be good if they managed the gh project/issues list for us

**Comment by kreig303** [comment]
Jackson Fratesi:
> could we add language to the sign up form asking people to sign up for slack FIRST? I see that we are already asking people to use the email associated.

@maybejustmaybe:
>There is also another piece to this: the current zapier automation takes up to 15 minutes to populate the slack ID after a volunteer fills out the form.
