### ISSUE TITLE
Intake Ticket Assigned trigger

### ISSUE THREAD

**Issue by cubeghost** [bedstuystrong/firebase-functions#4]
Airtable ➡️Slack

- #### Updates the neighborhood Slack post
  - Edits an emoji representing the ticket status
  - Posts a comment in the thread
- #### Sends delivery info to the volunteer, including information about the request
  - Ticket ID
  - Neighbor’s name
  - Neighbor’s contact info
  - Location
  - Time
  - Shopping list
  - FUTURE: bulk pickup locations
  - Delivery Volunteer FAQ
- #### Includes a link to a delivery volunteer request completion form
- #### Includes a delivery questions channel

**Comment by maybejustmaybe** [comment]
I'm going to wait to do the posting to a thread for now

**Comment by alyssadizon** [comment]
Message template for delivery volunteers! 
---

<@intake volunteer> assigned a request to you. Thanks so much for taking care of this delivery! 

**Ticket ID:** <ticket ID>

**Neighbor:** <neighbor name>
**Address:** <address>
**Phone:** <phone>

**Timeline:** <need immediacy>
**Need:** <need category>
**Description:** <task overview>
**Household size:** <household size>
**Requested:** <items/services requested> 

**Spending guidance:** 
- [if household size = 1 or 2 ppl] "$75/per person (1-2 ppl)" 
- [if household size = 3-5 ppl] "$250 for a medium household" 
- [if household size = 6+ ppl] "$350 for a large household (6+ ppl)" 
"Please try to buy about a week's worth of food for the household. It's ok if you can’t get every single thing on the shopping list -- the main goal is that the family’s nutritional needs are sufficiently met." 

**Language:** <language>
**FYI Special Conditions:** <vulnerabilities>

When you complete the delivery, please: 
1. Take a photo of the receipt 
2. Fill out [this reimbursement form](https://airtable.com/shrvHf4k5lRo0I8F4) and you will be reimbursed from our community fund within 24 hours.  
 
For guidance on how to do a no-contact delivery, check out our [Delivery Volunteer FAQ guide](https://docs.google.com/document/d/1-sXwubRG3yBw2URDYcrSGZSj94tY_Ydk4xxVDmgRFh8/edit?usp=sharing). 

If you have any questions/problems, please post in #delivery_volunteers. Thanks again for volunteering! 

_Reminder: Please don't volunteer for delivery if you've traveled out of the country in the last 14 days, have any COVID-19/cold/flu-like symptoms, or have come into contact with someone that's tested positive._ 

❤️ ❤️ ❤️
