### ISSUE TITLE
Missing COPYING and license info

### ISSUE THREAD

**Issue by pnasrat** [bedstuystrong/firebase-functions#45]
I'm starting to get involved with Clinton Hill and Fort Greene Mutual Aid and was pointed at your repository

It's not clear what license this is under so wanted to check before making modifications to our fork - I'm guessing something like MIT would fit if you haven't chosen one well but you can see options here

See https://choosealicense.com/ for more options

**Comment by leifwalsh** [comment]
This was handled in #60 and can be closed.
