### ISSUE TITLE
Delivery Completion form

### ISSUE THREAD

**Issue by cubeghost** [bedstuystrong/firebase-functions#6]
Includes a field for the “ticket ID” that the user will copy from the Slack DM
If the volunteer purchased goods, they will submit:
- a receipt photo
- Total cost (in $)
- Total personal donation towards cost (in $)
- Preferred payment platform
- Payment platform user account

Updates the Intake Ticket request status to: `completed`

**Comment by maybejustmaybe** [comment]
I'm going to wait to trigger a completion in the intake requests table when the user completes this request. Its slightly different that what we have done so far as it has to poll another table and change a ticket in the intake table.
