### ISSUE TITLE
Create workflow for assigning bulk delivery tickets

### ISSUE THREAD

**Issue by leifwalsh** [bedstuystrong/firebase-functions#62]
We need a way to identify which tickets will receive bulk delivery, represent clusters of nearby deliveries to assign to delivery volunteers, and before the day of delivery, generate an email per delivery volunteer with the list of tickets they've been assigned, with instructions and maybe directions.

The high level workflow will be:

1. When we select tickets for bulk delivery, change their Status from Seeking Volunteer to Bulk Delivery Scheduled (this way, the rest of the automation won't advertise them as seeking volunteers)
1. When we cluster tickets, set a new column Bulk Cluster to an id grouping those tickets
1. When we confirm the delivery window with the recipient, change the Status from Bulk Delivery Scheduled to Bulk Delivery Confirmed
1. When we assign delivery volunteers to bulk tickets, just set the Delivery Volunteer on that ticket
1. When we generate an email, do so for each Bulk Cluster id with Status = Bulk Delivery Confirmed, and verify that each group has the same delivery volunteer assigned
1. Other workflows should stay the same, for example when the delivery volunteer fills out the completion form, it should move the Status to Complete
1. We may want new views to manage the clustering and assignment process, we'll do this ad-hoc and formalize that later if needed

Tasks:

- [x] Add a Bulk Cluster column to the intake ticket table
- [x] Create views necessary for clustering and assigning
- [x] Write the code to find bulk tickets going out on a given week, and generate emails to their delivery volunteers

**Comment by hannashimona** [comment]
Bulk delivery statuses ("Bulk Delivery Scheduled" and "Bulk Delivery Confirmed" have been added to the volunteer status options.

**Comment by hannashimona** [comment]
Should Bulk Cluster be a text field, or an entity backed with a table? I'm inclined towards entity -- even if we don't currently make use of it, would be nice to have the option of populating metadata at the cluster level in the future. For example, car size needed to accommodate all boxes, sub-neighborhood of cluster, etc

**Comment by hannashimona** [comment]
Bulk Cluster has been created as a table-backed entity

**Comment by leifwalsh** [comment]
This is done, just need to merge #63 eventually.
