### ISSUE TITLE
send delivery volunteer a formatted shopping list

### ISSUE THREAD

**Issue by leifwalsh** [bedstuystrong/firebase-functions#71]
When Volunteer Bot DMs a volunteer after assignment, it could include a button that would cause the bot to split the list on commas to turn it into bullet points, and then send an email to the assigned volunteer on the ticket (this just makes it easier to copy/paste on your phone).

Alyssa suggests grouping by category (dairy, fruits & vegetables, ...), and maybe something to generate a shopping list for a volunteer who is shopping for multiple tickets in one trip to the store.

**Comment by leifwalsh** [comment]
We did something a little different for custom shoppers in service of bulk ordering, so this doesn't need to be on that milestone, but we should still do this for non-bulk tickets.

**Comment by mlauter** [comment]
closed by https://github.com/bedstuystrong/firebase-functions/pull/88
